name: format-and-lint-and-deploy

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  format-and-lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install linters
        run: |
          go get -u golang.org/x/lint/golint
          go get -u honnef.co/go/tools/cmd/staticcheck

      - name: Format code
        run: gofmt -s -w .

      - name: Add golint to PATH
        run: export PATH="/home/runner/go/bin:$PATH"
      
      - name: Debug PATH
        run: echo $PATH

      - name: List contents of /home/runner/go/bin
        run: ls /home/runner/go/bin

      - name: Lint code
        run: golint ./...

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t myapp .
          docker tag myapp:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
